import pandas as pd
mdd = pd.read_csv('estudiantes.csv')

print("\n**** EDAD ****")
maximo=(mdd["Edad"].max())
minimo=(mdd["Edad"].min())
#print("Maximo de edad:",maximo)
#print("Minimo de edad:",minimo)
Rango=(maximo-minimo)
print("El rango:",Rango)
varianza= mdd["Edad"].var()
print("La varianza:",varianza)
desviacion= mdd["Edad"].std()
print("La desviacion estandar:",desviacion)

print("\n**** ASISTENCIA ****")
maximo1=(mdd["Asistencia"].max())
minimo1=(mdd["Asistencia"].min())
Rango=(maximo1-minimo1)
print("El rango:",Rango)
varianza1= mdd["Asistencia"].var()
print("La varianza:",varianza1)
desviacion1= mdd["Asistencia"].std()
print("La desviacion estandar:",desviacion)

print("\n**** TAREAS ****")
maximo2=(mdd["Tareas"].max())
minimo2=(mdd["Tareas"].min())
Rango=(maximo2-minimo2)
print("El rango:",Rango)
varianza2= mdd["Tareas"].var()
print("La varianza:",varianza2)
desviacion2= mdd["Tareas"].std()
print("La desviacion estandar:",desviacion2)

print("\n**** EXAMEN ****")
maximo3=(mdd["Examen"].max())
minimo3=(mdd["Examen"].min())
Rango=(maximo3-minimo3)
print("El rango:",Rango)
varianza3= mdd["Examen"].var()
print("La varianza:",varianza3)
desviacion3= mdd["Examen"].std()
print("La desviacion estandar:",desviacion3)

print("\n**** CALIFICACION FINAL ****")
maximo4=(mdd["Calificacion_Final"].max())
minimo4=(mdd["Calificacion_Final"].min())
Rango=(maximo4-minimo4)
print("El rango:",Rango)
varianza4= mdd["Calificacion_Final"].var()
print("La varianza:",varianza4)
desviacion4= mdd["Calificacion_Final"].std()
print("La desviacion estandar:",desviacion)

print("\n**** HORAS DE ESTUDIO ****")
maximo5=(mdd["Horas_Estudio"].max())
minimo5=(mdd["Horas_Estudio"].min())
Rango=(maximo5-minimo5)
print("El rango:",Rango)
varianza5= mdd["Horas_Estudio"].var()
print("La varianza:",varianza5)
desviacion5= mdd["Horas_Estudio"].std()
print("La desviacion estandar:",desviacion5)